<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataDesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //database data desa seed
        DB::table('data_desa')->insert([
            // id kecamatan =>'1',

        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2001',
            'nama_desa'=>'Anjatan'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2010',
            'nama_desa'=>'Anjatan Baru'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2013',
            'nama_desa'=>'Anjatan Utara'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2003',
            'nama_desa'=>'Bugis'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2004',
            'nama_desa'=>'Bugis Tua'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2011',
            'nama_desa'=>'Cilandak'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2012',
            'nama_desa'=>'Cilandak Lor'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2006',
            'nama_desa'=>'Kedungwungu'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2009',
            'nama_desa'=>'Kopyah'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2008',
            'nama_desa'=>'Lempuyang'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2002',
            'nama_desa'=>'Mangunjaya'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2005',
            'nama_desa'=>'Salamdarma'
        ],
        [
            'id_kecamatan'=>'1',
            'kode_desa'=>'32.12.23.2007',
            'nama_desa'=>'Wanguk'
        ],

        // id kecamatan =>'2',

        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2001',
            'nama_desa'=>'Arahan Kidul'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2002',
            'nama_desa'=>'Arahan Lor'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2004',
            'nama_desa'=>'Cidempet'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2003',
            'nama_desa'=>'Linggajati'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2006',
            'nama_desa'=>'Pranggong'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2005',
            'nama_desa'=>'Sukadadi'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2007',
            'nama_desa'=>'Sukasari'
        ],
        [
            'id_kecamatan'=>'2',
            'kode_desa'=>'32.12.19.2008',
            'nama_desa'=>'Tawangsari'
        ],

        // id kecamatan =>'3',

        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2007',
            'nama_desa'=>'Balongan'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2005',
            'nama_desa'=>'Gelarmendala'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2008',
            'nama_desa'=>'Majakerta'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2004',
            'nama_desa'=>'Rawadalem'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2009',
            'nama_desa'=>'Sudimampir'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2010',
            'nama_desa'=>'Sudimampir Lor'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2002',
            'nama_desa'=>'Sukareja'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2003',
            'nama_desa'=>'Sukaurip'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2001',
            'nama_desa'=>'Tegal Sembadra'
        ],
        [
            'id_kecamatan'=>'3',
            'kode_desa'=>'32.12.14.2006',
            'nama_desa'=>'Tegalurung'
        ],

        // id kecamatan =>'4',

        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2015',
            'nama_desa'=>'Bangodua'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2016',
            'nama_desa'=>'Beduyut'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2019',
            'nama_desa'=>'Karanggetas'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2021',
            'nama_desa'=>'Malangsari'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2008',
            'nama_desa'=>'Mulyasari'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2017',
            'nama_desa'=>'Rancasari'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2020',
            'nama_desa'=>'Tegalgirang'
        ],
        [
            'id_kecamatan'=>'4',
            'kode_desa'=>'32.12.06.2018',
            'nama_desa'=>'Wanasari'
        ],

        // id_kecamatan =>'5',

        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2005',
            'nama_desa'=>'Bongas'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2006',
            'nama_desa'=>'Cipaat'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2001',
            'nama_desa'=>'Cipedang'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2004',
            'nama_desa'=>'Kertajaya'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2007',
            'nama_desa'=>'Kertamulya'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2003',
            'nama_desa'=>'Margamulya'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2008',
            'nama_desa'=>'Plawangan'
        ],
        [
            'id_kecamatan'=>'5',
            'kode_desa'=>'32.12.22.2002',
            'nama_desa'=>'Sidamulya'
        ],

        // id kecamatan =>'6',

        [
            'id_kecamatan'=>'6',
            'kode_desa'=>'32.12.17.2001',
            'nama_desa'=>'Cangkring'
        ],
        [
            'id_kecamatan'=>'6',
            'kode_desa'=>'32.12.17.2002',
            'nama_desa'=>'Cantigi Kulon'
        ],
        [
            'id_kecamatan'=>'6',
            'kode_desa'=>'32.12.17.2003',
            'nama_desa'=>'Cantigi Wetan'
        ],
        [
            'id_kecamatan'=>'6',
            'kode_desa'=>'32.12.17.2006',
            'nama_desa'=>'Lamarantarung'
        ],
        [
            'id_kecamatan'=>'6',
            'kode_desa'=>'32.12.17.2004',
            'nama_desa'=>'Panyingkiran Kidul'
        ],
        [
            'id_kecamatan'=>'6',
            'kode_desa'=>'32.12.17.2005',
            'nama_desa'=>'Panyingkiran Lor'
        ],

        // id kecamatan =>'7',

        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2004',
            'nama_desa'=>'Amis'
        ],
        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2012',
            'nama_desa'=>'Cikedung Lor'
        ],
        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2007',
            'nama_desa'=>'Cikidung Kidul'
        ],
        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2006',
            'nama_desa'=>'Jambak'
        ],
        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2005',
            'nama_desa'=>'Jatisura'
        ],
        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2003',
            'nama_desa'=>'Loyang'
        ],
        [
            'id_kecamatan'=>'7',
            'kode_desa'=>'32.12.04.2013',
            'nama_desa'=>'Mundakjaya'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2002',
            'nama_desa'=>'Babakan Jaya'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2010',
            'nama_desa'=>'Drunten Kulon'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2009',
            'nama_desa'=>'Drunten Wetan'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2003',
            'nama_desa'=>'Gabus Kulon'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2008',
            'nama_desa'=>'Gabus Wetan'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2005',
            'nama_desa'=>'Kedokan Gabus'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2001',
            'nama_desa'=>'Kedung Dawa'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2007',
            'nama_desa'=>'Rancahan'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2006',
            'nama_desa'=>'Rancamulya'
        ],
        [
            'id_kecamatan'=>'8',
            'kode_desa'=>'32.12.03.2004',
            'nama_desa'=>'Sekar Mulya'
        ],

        // id kecamatan =>'9',
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2006',
            'nama_desa'=>'Balereja'
        ],
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2001',
            'nama_desa'=>'Bantarwaru'
        ],
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2004',
            'nama_desa'=>'Gantar'
        ],
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2003',
            'nama_desa'=>'Mekarjaya'
        ],
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2007',
            'nama_desa'=>'Mekarwaru'
        ],
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2002',
            'nama_desa'=>'Sanca'
        ],
        [
            'id_kecamatan'=>'9',
            'kode_desa'=>'32.12.25.2005',
            'nama_desa'=>'Situraja'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2013',
            'nama_desa'=>'Cipancuh'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2008',
            'nama_desa'=>'Haurgeulis'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2007',
            'nama_desa'=>'Haurkolot'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2011',
            'nama_desa'=>'Karangtumaritis'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2012',
            'nama_desa'=>'Kertanegara'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2014',
            'nama_desa'=>'Mekarjati'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2015',
            'nama_desa'=>'Sidodadi'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2009',
            'nama_desa'=>'Sukajati'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2016',
            'nama_desa'=>'Sumbermulya'
        ],
        [
            'id_kecamatan'=>'10',
            'kode_desa'=>'32.12.01.2010',
            'nama_desa'=>'Wanakaya'
        ],

        // id kecamatan =>'11',
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2011',
            'nama_desa'=>'Dukuh'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2016',
            'nama_desa'=>'Karangsong'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2017',
            'nama_desa'=>'Pabean Udik'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2015',
            'nama_desa'=>'Pekandangan'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2012',
            'nama_desa'=>'Pekandangan Jaya'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2010',
            'nama_desa'=>'Plumbon'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2014',
            'nama_desa'=>'Singajaya'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2013',
            'nama_desa'=>'Singaraja'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2020',
            'nama_desa'=>'Tambak'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.2009',
            'nama_desa'=>'Telukagung'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1001',
            'nama_desa'=>'Kel. Bojongsari'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1004',
            'nama_desa'=>'Kel. Karanganyar'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1003',
            'nama_desa'=>'Kel. Karangmalang'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1002',
            'nama_desa'=>'Kel. Kepandean'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1006',
            'nama_desa'=>'Kel. Lemahabang'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1005',
            'nama_desa'=>'Kel. Lemahmekar'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1007',
            'nama_desa'=>'Kel. Margadadi'
        ],
        [
            'id_kecamatan'=>'11',
            'kode_desa'=>'32.12.15.1008',
            'nama_desa'=>'Kel. Paoman'
        ],

        // id kecamatan =>'12',
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2004',
            'nama_desa'=>'Bulak'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2005',
            'nama_desa'=>'Bulak Lor'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2006',
            'nama_desa'=>'Jatibarang'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2003',
            'nama_desa'=>'Jatibarang Baru'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2009',
            'nama_desa'=>'Jatisawit'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2010',
            'nama_desa'=>'Jatisawit Lor'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2012',
            'nama_desa'=>'Kalimati'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2007',
            'nama_desa'=>'Kebulen'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2011',
            'nama_desa'=>'Krasak'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2014',
            'nama_desa'=>'Lohbener'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2015',
            'nama_desa'=>'Lohbener Lor'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2013',
            'nama_desa'=>'Malang Semirang'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2008',
            'nama_desa'=>'Pawidean'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2002',
            'nama_desa'=>'Pilangsari'
        ],
        [
            'id_kecamatan'=>'12',
            'kode_desa'=>'32.12.13.2001',
            'nama_desa'=>'Sukalila'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2008',
            'nama_desa'=>'Dadap'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2010',
            'nama_desa'=>'Juntikebon'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2006',
            'nama_desa'=>'Juntikedokan'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2003',
            'nama_desa'=>'Juntiweden'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2005',
            'nama_desa'=>'Juntinyuat'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2012',
            'nama_desa'=>'Limbangan'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2011',
            'nama_desa'=>'Lombang'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2007',
            'nama_desa'=>'Pondoh'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2008',
            'nama_desa'=>'Sambirmaya'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2002',
            'nama_desa'=>'Segeran'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2001',
            'nama_desa'=>'Segeran Kidul'
        ],
        [
            'id_kecamatan'=>'13',
            'kode_desa'=>'32.12.11.2009',
            'nama_desa'=>'Tinumpuk'
        ],

        // kecamatan kandanghaur
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2008',
            'nama_desa'=>'Bulak'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2001',
            'nama_desa'=>'Curug'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2012',
            'nama_desa'=>'Eretan Kulon'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2011',
            'nama_desa'=>'Eretan Wetan'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2009',
            'nama_desa'=>'Ilir'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2005',
            'nama_desa'=>'Karang Anyar'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2004',
            'nama_desa'=>'Karangmulya'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2013',
            'nama_desa'=>'Kertawinangun'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2007',
            'nama_desa'=>'Pareangirang'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2002',
            'nama_desa'=>'Pranti'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2010',
            'nama_desa'=>'Soge'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2003',
            'nama_desa'=>'Wirakanan'
        ],
        [
            'id_kecamatan'=>'14',
            'kode_desa'=>'32.12.21.2006',
            'nama_desa'=>'Wirapanjunan'
        ],

        // id kecamatan =>'15',
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2011',
            'nama_desa'=>'Benda'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2015',
            'nama_desa'=>'Dukuh Jeruk'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2016',
            'nama_desa'=>'Dukuh Tengah'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2019',
            'nama_desa'=>'Kaplongan Lor'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2014',
            'nama_desa'=>'Karangampel'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2013',
            'nama_desa'=>'Karangampel Kidul'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2017',
            'nama_desa'=>'Mundu'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2010',
            'nama_desa'=>'Pringgacala'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2012',
            'nama_desa'=>'Sendang'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2008',
            'nama_desa'=>'Tanjungpura'
        ],
        [
            'id_kecamatan'=>'15',
            'kode_desa'=>'32.12.10.2009',
            'nama_desa'=>'Tanjungsari'
        ],

        // id kecamatan =>'16',
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2001',
            'nama_desa'=>'Cangkingan'
        ],
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2007',
            'nama_desa'=>'Jayalaksana'
        ],
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2002',
            'nama_desa'=>'Jayawinangun'
        ],
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2006',
            'nama_desa'=>'Kaplongan'
        ],
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2003',
            'nama_desa'=>'Kedokan Agung'
        ],
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2004',
            'nama_desa'=>'Kedokanbunder'
        ],
        [
            'id_kecamatan'=>'16',
            'kode_desa'=>'32.12.28.2005',
            'nama_desa'=>'Kedokanbunderwetan'
        ],

        //'id_kecamatan'=>'17',
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2011',
            'nama_desa'=>'Jambe'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2008',
            'nama_desa'=>'Jengkok'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2014',
            'nama_desa'=>'Kertasemaya'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2015',
            'nama_desa'=>'Kliwed'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2017',
            'nama_desa'=>'Larangan Jambe'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2012',
            'nama_desa'=>'Lemahayu'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2010',
            'nama_desa'=>'Manguntara'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2019',
            'nama_desa'=>'Sukawera'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2009',
            'nama_desa'=>'Tegal Wirangrong'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2016',
            'nama_desa'=>'Tenajar'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2013',
            'nama_desa'=>'Tenajar Kidul'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2018',
            'nama_desa'=>'Tenajar Lor'
        ],
        [
            'id_kecamatan'=>'17',
            'kode_desa'=>'32.12.08.2007',
            'nama_desa'=>'Tulungagung'
        ],

        // id kecamatan =>'18',
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2004',
            'nama_desa'=>'Dukuhjati'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2009',
            'nama_desa'=>'Kalianyar'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2002',
            'nama_desa'=>'Kapringan'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2006',
            'nama_desa'=>'Kedungwungu'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2010',
            'nama_desa'=>'Krangkeng'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2008',
            'nama_desa'=>'Luwunggesik'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2001',
            'nama_desa'=>'Purwajaya'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2003',
            'nama_desa'=>'Singakerta'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2007',
            'nama_desa'=>'Srengseng'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2011',
            'nama_desa'=>'Tanjakan'
        ],
        [
            'id_kecamatan'=>'18',
            'kode_desa'=>'32.12.09.2005',
            'nama_desa'=>'Tegalmulya'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2010',
            'nama_desa'=>'Jayamulya'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2002',
            'nama_desa'=>'Kroya'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2008',
            'nama_desa'=>'Suka Slamet'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2004',
            'nama_desa'=>'Sukamelang'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2009',
            'nama_desa'=>'Sumberjaya'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2003',
            'nama_desa'=>'Sumbon'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2006',
            'nama_desa'=>'Temiyangsari'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2001',
            'nama_desa'=>'Tanjungngkerta'
        ],
        [
            'id_kecamatan'=>'19',
            'kode_desa'=>'32.12.02.2005',
            'nama_desa'=>'Temiyang'
        ],

        // id kecamatan =>'20'
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2010',
            'nama_desa'=>'Cempeh'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2007',
            'nama_desa'=>'Langgengsari'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2009',
            'nama_desa'=>'Lelea'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2003',
            'nama_desa'=>'Nunuk'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2005',
            'nama_desa'=>'Pangauban'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2008',
            'nama_desa'=>'Tamansari'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2006',
            'nama_desa'=>'Tegalasari'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2004',
            'nama_desa'=>'Tempel'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2011',
            'nama_desa'=>'Tempelkulon'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2002',
            'nama_desa'=>'Tugu'
        ],
        [
            'id_kecamatan'=>'20',
            'kode_desa'=>'32.12.05.2001',
            'nama_desa'=>'Tunggul Payung'
        ],

        // 'id_kecamatan'=>'21',
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2008',
            'nama_desa'=>'Bojongslawi'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2002',
            'nama_desa'=>'Kiajaran Kulon'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2001',
            'nama_desa'=>'Kiajaran Wetan'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2004',
            'nama_desa'=>'Langut'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2003',
            'nama_desa'=>'Lanjan'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2005',
            'nama_desa'=>'Larangan'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2007',
            'nama_desa'=>'Legok'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2009',
            'nama_desa'=>'Lohbener'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2010',
            'nama_desa'=>'Pamayahan'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2012',
            'nama_desa'=>'Rambatan Kulon'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2011',
            'nama_desa'=>'Sindangkerta'
        ],
        [
            'id_kecamatan'=>'21',
            'kode_desa'=>'32.12.18.2006',
            'nama_desa'=>'Waru'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2009',
            'nama_desa'=>'Cemara'
        ],
        // 'id_kecamatan'=>'22',
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2013',
            'nama_desa'=>'Cemara Kulon'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2006',
            'nama_desa'=>'Jangga'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2007',
            'nama_desa'=>'Jumbleng'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2002',
            'nama_desa'=>'Krimun'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2010',
            'nama_desa'=>'Losarang'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2011',
            'nama_desa'=>'Muntur'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2008',
            'nama_desa'=>'Pangkalan'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2004',
            'nama_desa'=>'Pegagan'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2003',
            'nama_desa'=>'Puntang'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2005',
            'nama_desa'=>'Rajaiyang'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2001',
            'nama_desa'=>'Ranjeng'
        ],
        [
            'id_kecamatan'=>'22',
            'kode_desa'=>'32.12.20.2012',
            'nama_desa'=>'Santing'
        ],

        // id kecamatan =>'23',
        [
            'id_kecamatan'=>'23',
            'kode_desa'=>'32.12.29.2001',
            'nama_desa'=>'Brondong'
        ],
        [
            'id_kecamatan'=>'23',
            'kode_desa'=>'32.12.29.2005',
            'nama_desa'=>'Karanganyar'
        ],
        [
            'id_kecamatan'=>'23',
            'kode_desa'=>'32.12.29.2002',
            'nama_desa'=>'Pabean Ilir'
        ],
        [
            'id_kecamatan'=>'23',
            'kode_desa'=>'32.12.29.2003',
            'nama_desa'=>'Pagirikan'
        ],
        [
            'id_kecamatan'=>'23',
            'kode_desa'=>'32.12.29.2004',
            'nama_desa'=>'Pasekan'
        ],
        [
            'id_kecamatan'=>'23',
            'kode_desa'=>'32.12.29.2006',
            'nama_desa'=>'Totoran'
        ],

        // 'id_kecamatan'=>'24'
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2007',
            'nama_desa'=>'Arjasari'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2006',
            'nama_desa'=>'Bugel'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2001',
            'nama_desa'=>'Limpas'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2002',
            'nama_desa'=>'Mekarsari'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2005',
            'nama_desa'=>'Patrol'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2003',
            'nama_desa'=>'Patrol Baru'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2004',
            'nama_desa'=>'Patrol Lor'
        ],
        [
            'id_kecamatan'=>'24',
            'kode_desa'=>'32.12.31.2008',
            'nama_desa'=>'Sukahaji'
        ],

        // 'id_kecamatan'=>'25',
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2009',
            'nama_desa'=>'Babadan'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2006',
            'nama_desa'=>'Dermayu'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2004',
            'nama_desa'=>'Kenanga'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2001',
            'nama_desa'=>'Panyindangan Kulon'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2003',
            'nama_desa'=>'Panyindangan Wetan'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2008',
            'nama_desa'=>'Penganjang'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2002',
            'nama_desa'=>'Rambatan Wetan'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2007',
            'nama_desa'=>'Sindang'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2005',
            'nama_desa'=>'Terusan'
        ],
        [
            'id_kecamatan'=>'25',
            'kode_desa'=>'32.12.16.2014',
            'nama_desa'=>'Wanantara'
        ],

        // 'id_kecamatan'=>'26',
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2002',
            'nama_desa'=>'Gadingan'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2016',
            'nama_desa'=>'Longok'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2006',
            'nama_desa'=>'Majasari'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2007',
            'nama_desa'=>'Majasih'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2010',
            'nama_desa'=>'Mekargading'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2001',
            'nama_desa'=>'Sleman'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2005',
            'nama_desa'=>'Sleman Lor'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2008',
            'nama_desa'=>'Sliyeg'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2011',
            'nama_desa'=>'Sliyeg Lor'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2003',
            'nama_desa'=>'Sudikampiran'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2002',
            'nama_desa'=>'Tambi'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2004',
            'nama_desa'=>'Tambi Lor
            '
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2013',
            'nama_desa'=>'Tugu'
        ],
        [
            'id_kecamatan'=>'26',
            'kode_desa'=>'32.12.12.2012',
            'nama_desa'=>'Tugukidul'
        ],
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2002',
            'nama_desa'=>'Bondan'
        ],

        // 'id_kecamatan'=>'27',
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2006',
            'nama_desa'=>'Cadang Pinggan'
        ],
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2001',
            'nama_desa'=>'Cibeber'
        ],
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2007',
            'nama_desa'=>'Gedangan'
        ],
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2003',
            'nama_desa'=>'Gunungsari'
        ],
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2004',
            'nama_desa'=>'Sukagumiwang'
        ],
        [
            'id_kecamatan'=>'27',
            'kode_desa'=>'32.12.27.2005',
            'nama_desa'=>'Tersana'
        ],

        // 'id_kecamatan'=>'28',
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2001',
            'nama_desa'=>'Bogor'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2017',
            'nama_desa'=>'Karang Layung'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2002',
            'nama_desa'=>'Sukra'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2005',
            'nama_desa'=>'Sukrawetan'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2006',
            'nama_desa'=>'Sumuradem'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2007',
            'nama_desa'=>'Sumuradem Timur'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2004',
            'nama_desa'=>'Tagal Taman'
        ],
        [
            'id_kecamatan'=>'28',
            'kode_desa'=>'32.12.24.2003',
            'nama_desa'=>'Ujunggebang'
        ],

        // 'id_kecamatan'=>'29',
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2007',
            'nama_desa'=>'Cibereng'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2001',
            'nama_desa'=>'Cikawung'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2002',
            'nama_desa'=>'Jatimulya'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2003',
            'nama_desa'=>'Jatimunggul'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2006',
            'nama_desa'=>'Karangasem'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2008',
            'nama_desa'=>'Kendayakan'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2009',
            'nama_desa'=>'Manggungan'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2004',
            'nama_desa'=>'Plosokerep'
        ],
        [
            'id_kecamatan'=>'29',
            'kode_desa'=>'32.12.26.2005',
            'nama_desa'=>'Rajasinga'
        ],

        // 'id_kecamatan'=>'30',
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2001',
            'nama_desa'=>'Bodas'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2005',
            'nama_desa'=>'Cangko'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2002',
            'nama_desa'=>'Gadel'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2006',
            'nama_desa'=>'Karangkerta'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2004',
            'nama_desa'=>'Kerticala'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2009',
            'nama_desa'=>'Lajer'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2008',
            'nama_desa'=>'Mekarsari'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2012',
            'nama_desa'=>'Pagedangan'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2003',
            'nama_desa'=>'Rancajawat'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2011',
            'nama_desa'=>'Sukadana'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2007',
            'nama_desa'=>'Sukamulya'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2013',
            'nama_desa'=>'Sukaperna'
        ],
        [
            'id_kecamatan'=>'30',
            'kode_desa'=>'32.12.30.2010',
            'nama_desa'=>'Tukdana'
        ],

        // 'id_kecamatan'=>'31',
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2006',
            'nama_desa'=>'Bangkaloa Ilir'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2010',
            'nama_desa'=>'Bunder'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2008',
            'nama_desa'=>'Kalensari'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2016',
            'nama_desa'=>'Kasmaran'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2012',
            'nama_desa'=>'Kongsijaya'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2015',
            'nama_desa'=>'Leuwigede'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2014',
            'nama_desa'=>'Ujung Pondok Jaya'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2011',
            'nama_desa'=>'Ujungaris'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2013',
            'nama_desa'=>'Ujungjaya'
        ],
        [
            'id_kecamatan'=>'31',
            'kode_desa'=>'32.12.07.2007',
            'nama_desa'=>'Widasari'
        ]]
    );
    }
}
