<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataKecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //input data kecamatan
        DB::table('data_kecamatan')->insert([
        [
            'kode_kecamatan'=>'32.12.23',
            'nama_kecamatan'=>'Anjatan'
        ],
        [
            'kode_kecamatan'=>'32.12.19',
            'nama_kecamatan'=>'Arahan'
        ],
        [
            'kode_kecamatan'=>'32.12.14',
            'nama_kecamatan'=>'Balongan'
        ],
        [
            'kode_kecamatan'=>'32.12.06',
            'nama_kecamatan'=>'Bangodua'
        ],
        [
            'kode_kecamatan'=>'32.12.22',
            'nama_kecamatan'=>'Bongas'
        ],
        [
            'kode_kecamatan'=>'32.12.17',
            'nama_kecamatan'=>'Cantigi'
        ],
        [
            'kode_kecamatan'=>'32.12.04',
            'nama_kecamatan'=>'Cikedung'
        ],
        [
            'kode_kecamatan'=>'32.12.03',
            'nama_kecamatan'=>'Gabuswetan'
        ],
        [
            'kode_kecamatan'=>'32.12.25',
            'nama_kecamatan'=>'Gantar'
        ],
        [
            'kode_kecamatan'=>'32.12.01',
            'nama_kecamatan'=>'Haurgeulis'
        ],
        [
            'kode_kecamatan'=>'32.12.15',
            'nama_kecamatan'=>'Indramayu'
        ],
        [
            'kode_kecamatan'=>'32.12.13',
            'nama_kecamatan'=>'Jatibarang'
        ],
        [
            'kode_kecamatan'=>'32.12.11',
            'nama_kecamatan'=>'Juntinyuat'
        ],
        [
            'kode_kecamatan'=>'32.12.21',
            'nama_kecamatan'=>'Kandanghaur'
        ],
        [
            'kode_kecamatan'=>'32.12.10',
            'nama_kecamatan'=>'Karangampel'
        ],
        [
            'kode_kecamatan'=>'32.12.28',
            'nama_kecamatan'=>'Kedokan Bunder'
        ],
        [
            'kode_kecamatan'=>'32.12.08',
            'nama_kecamatan'=>'Kertasemaya'
        ],
        [
            'kode_kecamatan'=>'32.12.09',
            'nama_kecamatan'=>'Krangkeng'
        ],
        [
            'kode_kecamatan'=>'32.12.02',
            'nama_kecamatan'=>'Kroya'
        ],
        [
            'kode_kecamatan'=>'32.12.05',
            'nama_kecamatan'=>'Lelea'
        ],
        [
            'kode_kecamatan'=>'32.12.18',
            'nama_kecamatan'=>'Lohbener'
        ],
        [
            'kode_kecamatan'=>'32.12.20',
            'nama_kecamatan'=>'Losarang'
        ],
        [
            'kode_kecamatan'=>'32.12.29',
            'nama_kecamatan'=>'Pasekan'
        ],
        [
            'kode_kecamatan'=>'32.12.31',
            'nama_kecamatan'=>'Patrol'
        ],
        [
            'kode_kecamatan'=>'32.12.16',
            'nama_kecamatan'=>'Sindang'
        ],
        [
            'kode_kecamatan'=>'32.12.12',
            'nama_kecamatan'=>'Sliyeg'
        ],
        [
            'kode_kecamatan'=>'32.12.27',
            'nama_kecamatan'=>'Sukagumiwang'
        ],
        [
            'kode_kecamatan'=>'32.12.24',
            'nama_kecamatan'=>'Sukra'
        ],
        [
            'kode_kecamatan'=>'32.12.26',
            'nama_kecamatan'=>'Trisi'
        ],
        [
            'kode_kecamatan'=>'32.12.30',
            'nama_kecamatan'=>'Tukdana'
        ],
        [
            'kode_kecamatan'=>'32.12.07',
            'nama_kecamatan'=>'Widasari'
        ]
        ]);
    }
}
